version: '3'
services:
    employeecare:
        container_name: employeecare
        image: 100598/employeecare:1.0
        ports: 
        - 8080:8080
    mysql:
        container_name: employeecare-db
        image: mysql:5.7
        environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_USER=root
        - MYSQL_PASSWORD=root
        - MYSQL_DATABASE=EMPLOYEECARE
        volumes:
        - appvolume:/var/lib/mysql
volumes:
    appvolume:  
