version: '3'
services:
    employeecare:
        container_name: employee-care
        image: {hub-username }/employee-care:1.0
        ports:
            - 8080:8080
    mysql:
        container_name: employee-care-db
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=user
            - MYSQL_PASSWORD=pass
            - MYSQL_DATABASE=employee_care
        volumes:
            - appvolume:/var/lib/mysql
        ports:
            - "3306:3306"
volumes:
    appvolume:  
